name: Node.js CI/CD Pipeline

on: [push]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - run: echo "✅ Repository checked out successfully!"

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: echo "✅ Node.js set up successfully!"

    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: echo "✅ Node.js modules cached successfully!"

    - name: Install Dependencies
      run: |
        npm install
        echo "✅ Dependencies installed successfully!"

    - name: Lint Code
      run: |
        npm run lint
        echo "✅ Code linted successfully!"

    - name: AWS CDK Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-2'
      run: |
        npm install -g aws-cdk
        cdk deploy --require-approval never
        echo "✅ Deployment completed successfully!"
